### ISSUE TITLE
registerForRemoteNotificationTypes and xcode 6.1

### ISSUE THREAD

**Issue by vittoriofoschi** [strongloop/loopback-sdk-ios#32]
The method registerForRemoteNotificationTypes is not compatible with ios8 and Xcode 6.1

**Comment by carliwis** [comment]
nobody answers the issues =/

**Comment by hideya** [comment]
The following fix has to be applied to `LBPushNotification.m` too:
https://github.com/strongloop/loopback-component-push/pull/67/files

**Comment by hideya** [comment]
I confirmed that the issue still exists in the SDK codebase (although the same issue has been fixed in loopback-component-push/example/ios).  The framework keeps running even with the issue but it emits "registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later" to the debug console. This better be fixed soon.

**Comment by hideya** [comment]
Now I see the issue has inappropriately been fixed inside the iOS push notification sample app...

**Comment by hideya** [comment]
The issue has been fixed by https://github.com/strongloop/loopback-sdk-ios/pull/38
Thanks for pointing it out!

**Comment by bajtos** [comment]
I am closing the issue then. @raymondfeng could you please make a new release of the SDK?
