### ISSUE TITLE
LBInstallation _id not set

### ISSUE THREAD

**Issue by behrad** [strongloop/loopback-sdk-ios#51]
After updating to the latest version of sdk, my code broke when working with LBInstallation. After digging into it found that it should be related to #40 
I have 2 issues:

1) after `registerDeviceWithAdapter` in success callback, `mode._id` got to null

2) when re-registring (updating an LBInstallation) loopback tries to create existing model here
https://github.com/strongloop/loopback-sdk-ios/blob/master/LoopBack/LBPersistedModel.m#L39
again since `self._id` is null

My code was working with old version of SDK, found no documentation about this... or how to write against the new changes.

**Comment by hideya** [comment]
@behrad Thank you for reporting the issue.  I'll look into the cause soon.  Sorry for any inconvenience...

**Comment by hideya** [comment]
@behrad I quickly checked the unit test for `registerDeviceWithAdapter` against the current SDK and found it is successful, meaning `model._id` holds a valid number:
https://github.com/strongloop/loopback-sdk-ios/blob/master/LoopBackTests/LBInstallationTests.m#L67-L86

Since `LBInstallation` is a `PersistedModel`, #40 is not supposed to change any of its behavior (except its superclass change).  Actually, the only change I needed to make against the unit tests for `LBInstallation` after #40 is this change from `LBModel` to `LBPersistedModel`: https://github.com/strongloop/loopback-sdk-ios/blob/master/LoopBackTests/LBInstallationTests.m#L141

With these info, could you think of the reason why it is broken against your code but runs OK against the unit test?

**Comment by behrad** [comment]
we first changed `model._id` to `[model.toDictionary valueForKey:@"id"]` and it retrieved the value, One of our guys added this to https://github.com/strongloop/loopback-sdk-ios/blob/master/LoopBack/LBPersistedModel.m#L24
```objectiveC
@synthesize _id = __id;

- (id)_id{
    return __id;
}
```

and it worked!!

**Comment by hideya** [comment]
Thanks @behrad for getting back to me with the successfully modified code.   I'm not sure why the issue didn't reproduce on my side, but having explicit `@synthesize _id = __id;` is a good idea (even without it, automatic synthesis should happen, but the code shouldn't have assumed the instance variable name that is used for storage).

Could I ask you one change?  Could you please add just `@synthesize _id = __id;` only at Line 24 and see if it still works? (it should, since the getter should have been generated by the `@synthesize` directive).

**Comment by behrad** [comment]
> Could I ask you one change? Could you please add just @synthesize _id = __id; only at Line 24 and see if it still works?

Yes, only adding `@synthesize _id = __id;` makes it work for me!

**Comment by hideya** [comment]
Thank you, @behrad !  Then we should add the line there.  Would you like to file a Pull Request for the change?  If so, please go ahead.  If you'd like me to take care of it, I'm happy to do so.  Please let me know.

**Comment by behrad** [comment]
Since I'm not the main developer of our IOS code, I'd be happy if you can take care of it. Thank you for your fast response @hideya

**Comment by hideya** [comment]
You are very welcome, @behrad.  Sounds good to me.  I'll take care of it as the first thing tomorrow!

**Comment by behrad** [comment]
:+1:

**Comment by hideya** [comment]
I just filed PR https://github.com/strongloop/loopback-sdk-ios/pull/52 .  
Thank you @behrad for all the help!
