### ISSUE TITLE
Can not subclass LBUserRepository in swift

### ISSUE THREAD

**Issue by Vincentjonssonqi** [strongloop/loopback-sdk-ios#69]
```Swift
class CustomerRepository:LBUserRepository {
    override class func repository() -> CustomerRepository {
        let repo = CustomerRepository(className: "Customer")
        return repo
    }
}
```

Tried to subclass LBUserRepository but I keep getting this error: "Cannot override 'repository' which has been marked unavailable"
What am I missing?

**Comment by hideya** [comment]
`repository` method's return type is `instancetype`
So, maybe try `override class func repository() -> Self {` ?

**Comment by Vincentjonssonqi** [comment]
Thanks for the answer but by doing so it produces yet an error: "Expected type for function result"

**Comment by hideya** [comment]
@Vincentjonssonqi , did you find any solution for it or cause of the issue?  
I finally had a chance to try the code and reproduced it, and am having a difficulty to find a solution...

**Comment by hideya** [comment]
I figured out the situation.  The complication is caused by Swift's automatic remapping of Obj-C factory methods to Swift constructors when importing Obj-C classes (for details see [this SO post](http://stackoverflow.com/questions/26818432/how-to-call-an-objective-c-class-method-in-swift)).

So, the definition of `CustomerRepository` would look like the following:
```swift
class CustomerRepository:LBUserRepository {
    override init() {
        super.init(className: "Customer")
    }
}
```
and its usage would look like the following:
```swift
let repo = CustomerRepository()  // not CustomerRepository.repository() 
```
Hope this fully solves the issue...

**Comment by Vincentjonssonqi** [comment]
I solved it by using a subclass of User as user on the server. the iOS sdk started using my user (small U) subclass without me needing to subclass LBUserRepository on the client. Thank you for taking time to look into this.
